version: '2.1'

services:
  peterpilgrim:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/labs2/peterpilgrim
    ports:
      - $SERVER_PORT:$SERVER_PORT
